apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-caching
  namespace: cicd-pipeline-demo
  labels:
    app.kubernetes.io/version: '0.4'
spec:
  description: >-
    This Task can be used to run a Maven build. The only difference to  the
    original one from github.com/tektoncd/catalog is that it uses an  optional
    local maven repo path to cache all the dependencies. And it requires a a
    maven-settings workspace. 
  params:
    - default:
        - package
      description: maven goals to run
      name: GOALS
      type: array
    - default: .
      description: >-
        The context directory within the repository for sources on which we want
        to execute maven goals.
      name: CONTEXT_DIR
      type: string
  steps:
    - args:
        - '-Dmaven.repo.local=$(workspaces.source.path)'
        - $(params.GOALS)
      command:
        - /usr/bin/mvn
      image: >-
        gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
      name: mvn-goals
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
  workspaces:
    - description: The workspace consisting of maven project.
      name: source

